/**
 * Location data for country and city selection
 * Contains all world countries and major cities
 */

export interface Country {
  code: string;
  name: string;
}

export interface City {
  name: string;
  country: string;
  countryCode: string;
}

// All world countries (ISO 3166-1 alpha-2)
export const COUNTRIES: Country[] = [
  { code: 'AF', name: 'Afghanistan' },
  { code: 'AL', name: 'Albania' },
  { code: 'DZ', name: 'Algeria' },
  { code: 'AD', name: 'Andorra' },
  { code: 'AO', name: 'Angola' },
  { code: 'AG', name: 'Antigua and Barbuda' },
  { code: 'AR', name: 'Argentina' },
  { code: 'AM', name: 'Armenia' },
  { code: 'AU', name: 'Australia' },
  { code: 'AT', name: 'Austria' },
  { code: 'AZ', name: 'Azerbaijan' },
  { code: 'BS', name: 'Bahamas' },
  { code: 'BH', name: 'Bahrain' },
  { code: 'BD', name: 'Bangladesh' },
  { code: 'BB', name: 'Barbados' },
  { code: 'BY', name: 'Belarus' },
  { code: 'BE', name: 'Belgium' },
  { code: 'BZ', name: 'Belize' },
  { code: 'BJ', name: 'Benin' },
  { code: 'BT', name: 'Bhutan' },
  { code: 'BO', name: 'Bolivia' },
  { code: 'BA', name: 'Bosnia and Herzegovina' },
  { code: 'BW', name: 'Botswana' },
  { code: 'BR', name: 'Brazil' },
  { code: 'BN', name: 'Brunei' },
  { code: 'BG', name: 'Bulgaria' },
  { code: 'BF', name: 'Burkina Faso' },
  { code: 'BI', name: 'Burundi' },
  { code: 'CV', name: 'Cabo Verde' },
  { code: 'KH', name: 'Cambodia' },
  { code: 'CM', name: 'Cameroon' },
  { code: 'CA', name: 'Canada' },
  { code: 'CF', name: 'Central African Republic' },
  { code: 'TD', name: 'Chad' },
  { code: 'CL', name: 'Chile' },
  { code: 'CN', name: 'China' },
  { code: 'CO', name: 'Colombia' },
  { code: 'KM', name: 'Comoros' },
  { code: 'CG', name: 'Congo' },
  { code: 'CD', name: 'Congo (Democratic Republic)' },
  { code: 'CR', name: 'Costa Rica' },
  { code: 'CI', name: "Cote d'Ivoire" },
  { code: 'HR', name: 'Croatia' },
  { code: 'CU', name: 'Cuba' },
  { code: 'CY', name: 'Cyprus' },
  { code: 'CZ', name: 'Czech Republic' },
  { code: 'DK', name: 'Denmark' },
  { code: 'DJ', name: 'Djibouti' },
  { code: 'DM', name: 'Dominica' },
  { code: 'DO', name: 'Dominican Republic' },
  { code: 'EC', name: 'Ecuador' },
  { code: 'EG', name: 'Egypt' },
  { code: 'SV', name: 'El Salvador' },
  { code: 'GQ', name: 'Equatorial Guinea' },
  { code: 'ER', name: 'Eritrea' },
  { code: 'EE', name: 'Estonia' },
  { code: 'SZ', name: 'Eswatini' },
  { code: 'ET', name: 'Ethiopia' },
  { code: 'FJ', name: 'Fiji' },
  { code: 'FI', name: 'Finland' },
  { code: 'FR', name: 'France' },
  { code: 'GA', name: 'Gabon' },
  { code: 'GM', name: 'Gambia' },
  { code: 'GE', name: 'Georgia' },
  { code: 'DE', name: 'Germany' },
  { code: 'GH', name: 'Ghana' },
  { code: 'GR', name: 'Greece' },
  { code: 'GD', name: 'Grenada' },
  { code: 'GT', name: 'Guatemala' },
  { code: 'GN', name: 'Guinea' },
  { code: 'GW', name: 'Guinea-Bissau' },
  { code: 'GY', name: 'Guyana' },
  { code: 'HT', name: 'Haiti' },
  { code: 'HN', name: 'Honduras' },
  { code: 'HU', name: 'Hungary' },
  { code: 'IS', name: 'Iceland' },
  { code: 'IN', name: 'India' },
  { code: 'ID', name: 'Indonesia' },
  { code: 'IR', name: 'Iran' },
  { code: 'IQ', name: 'Iraq' },
  { code: 'IE', name: 'Ireland' },
  { code: 'IL', name: 'Israel' },
  { code: 'IT', name: 'Italy' },
  { code: 'JM', name: 'Jamaica' },
  { code: 'JP', name: 'Japan' },
  { code: 'JO', name: 'Jordan' },
  { code: 'KZ', name: 'Kazakhstan' },
  { code: 'KE', name: 'Kenya' },
  { code: 'KI', name: 'Kiribati' },
  { code: 'KP', name: 'Korea (North)' },
  { code: 'KR', name: 'Korea (South)' },
  { code: 'KW', name: 'Kuwait' },
  { code: 'KG', name: 'Kyrgyzstan' },
  { code: 'LA', name: 'Laos' },
  { code: 'LV', name: 'Latvia' },
  { code: 'LB', name: 'Lebanon' },
  { code: 'LS', name: 'Lesotho' },
  { code: 'LR', name: 'Liberia' },
  { code: 'LY', name: 'Libya' },
  { code: 'LI', name: 'Liechtenstein' },
  { code: 'LT', name: 'Lithuania' },
  { code: 'LU', name: 'Luxembourg' },
  { code: 'MG', name: 'Madagascar' },
  { code: 'MW', name: 'Malawi' },
  { code: 'MY', name: 'Malaysia' },
  { code: 'MV', name: 'Maldives' },
  { code: 'ML', name: 'Mali' },
  { code: 'MT', name: 'Malta' },
  { code: 'MH', name: 'Marshall Islands' },
  { code: 'MR', name: 'Mauritania' },
  { code: 'MU', name: 'Mauritius' },
  { code: 'MX', name: 'Mexico' },
  { code: 'FM', name: 'Micronesia' },
  { code: 'MD', name: 'Moldova' },
  { code: 'MC', name: 'Monaco' },
  { code: 'MN', name: 'Mongolia' },
  { code: 'ME', name: 'Montenegro' },
  { code: 'MA', name: 'Morocco' },
  { code: 'MZ', name: 'Mozambique' },
  { code: 'MM', name: 'Myanmar' },
  { code: 'NA', name: 'Namibia' },
  { code: 'NR', name: 'Nauru' },
  { code: 'NP', name: 'Nepal' },
  { code: 'NL', name: 'Netherlands' },
  { code: 'NZ', name: 'New Zealand' },
  { code: 'NI', name: 'Nicaragua' },
  { code: 'NE', name: 'Niger' },
  { code: 'NG', name: 'Nigeria' },
  { code: 'MK', name: 'North Macedonia' },
  { code: 'NO', name: 'Norway' },
  { code: 'OM', name: 'Oman' },
  { code: 'PK', name: 'Pakistan' },
  { code: 'PW', name: 'Palau' },
  { code: 'PS', name: 'Palestine' },
  { code: 'PA', name: 'Panama' },
  { code: 'PG', name: 'Papua New Guinea' },
  { code: 'PY', name: 'Paraguay' },
  { code: 'PE', name: 'Peru' },
  { code: 'PH', name: 'Philippines' },
  { code: 'PL', name: 'Poland' },
  { code: 'PT', name: 'Portugal' },
  { code: 'QA', name: 'Qatar' },
  { code: 'RO', name: 'Romania' },
  { code: 'RU', name: 'Russia' },
  { code: 'RW', name: 'Rwanda' },
  { code: 'KN', name: 'Saint Kitts and Nevis' },
  { code: 'LC', name: 'Saint Lucia' },
  { code: 'VC', name: 'Saint Vincent and the Grenadines' },
  { code: 'WS', name: 'Samoa' },
  { code: 'SM', name: 'San Marino' },
  { code: 'ST', name: 'Sao Tome and Principe' },
  { code: 'SA', name: 'Saudi Arabia' },
  { code: 'SN', name: 'Senegal' },
  { code: 'RS', name: 'Serbia' },
  { code: 'SC', name: 'Seychelles' },
  { code: 'SL', name: 'Sierra Leone' },
  { code: 'SG', name: 'Singapore' },
  { code: 'SK', name: 'Slovakia' },
  { code: 'SI', name: 'Slovenia' },
  { code: 'SB', name: 'Solomon Islands' },
  { code: 'SO', name: 'Somalia' },
  { code: 'ZA', name: 'South Africa' },
  { code: 'SS', name: 'South Sudan' },
  { code: 'ES', name: 'Spain' },
  { code: 'LK', name: 'Sri Lanka' },
  { code: 'SD', name: 'Sudan' },
  { code: 'SR', name: 'Suriname' },
  { code: 'SE', name: 'Sweden' },
  { code: 'CH', name: 'Switzerland' },
  { code: 'SY', name: 'Syria' },
  { code: 'TW', name: 'Taiwan' },
  { code: 'TJ', name: 'Tajikistan' },
  { code: 'TZ', name: 'Tanzania' },
  { code: 'TH', name: 'Thailand' },
  { code: 'TL', name: 'Timor-Leste' },
  { code: 'TG', name: 'Togo' },
  { code: 'TO', name: 'Tonga' },
  { code: 'TT', name: 'Trinidad and Tobago' },
  { code: 'TN', name: 'Tunisia' },
  { code: 'TR', name: 'Turkey' },
  { code: 'TM', name: 'Turkmenistan' },
  { code: 'TV', name: 'Tuvalu' },
  { code: 'UG', name: 'Uganda' },
  { code: 'UA', name: 'Ukraine' },
  { code: 'AE', name: 'United Arab Emirates' },
  { code: 'GB', name: 'United Kingdom' },
  { code: 'US', name: 'United States' },
  { code: 'UY', name: 'Uruguay' },
  { code: 'UZ', name: 'Uzbekistan' },
  { code: 'VU', name: 'Vanuatu' },
  { code: 'VA', name: 'Vatican City' },
  { code: 'VE', name: 'Venezuela' },
  { code: 'VN', name: 'Vietnam' },
  { code: 'YE', name: 'Yemen' },
  { code: 'ZM', name: 'Zambia' },
  { code: 'ZW', name: 'Zimbabwe' },
];

// Major world cities (comprehensive list for job search context)
export const CITIES: City[] = [
  // Europe - Western
  { name: 'London', country: 'United Kingdom', countryCode: 'GB' },
  { name: 'Manchester', country: 'United Kingdom', countryCode: 'GB' },
  { name: 'Birmingham', country: 'United Kingdom', countryCode: 'GB' },
  { name: 'Edinburgh', country: 'United Kingdom', countryCode: 'GB' },
  { name: 'Glasgow', country: 'United Kingdom', countryCode: 'GB' },
  { name: 'Bristol', country: 'United Kingdom', countryCode: 'GB' },
  { name: 'Leeds', country: 'United Kingdom', countryCode: 'GB' },
  { name: 'Cambridge', country: 'United Kingdom', countryCode: 'GB' },
  { name: 'Oxford', country: 'United Kingdom', countryCode: 'GB' },
  { name: 'Paris', country: 'France', countryCode: 'FR' },
  { name: 'Lyon', country: 'France', countryCode: 'FR' },
  { name: 'Marseille', country: 'France', countryCode: 'FR' },
  { name: 'Toulouse', country: 'France', countryCode: 'FR' },
  { name: 'Nice', country: 'France', countryCode: 'FR' },
  { name: 'Bordeaux', country: 'France', countryCode: 'FR' },
  { name: 'Nantes', country: 'France', countryCode: 'FR' },
  { name: 'Lille', country: 'France', countryCode: 'FR' },
  { name: 'Strasbourg', country: 'France', countryCode: 'FR' },
  { name: 'Montpellier', country: 'France', countryCode: 'FR' },
  { name: 'Berlin', country: 'Germany', countryCode: 'DE' },
  { name: 'Munich', country: 'Germany', countryCode: 'DE' },
  { name: 'Frankfurt', country: 'Germany', countryCode: 'DE' },
  { name: 'Hamburg', country: 'Germany', countryCode: 'DE' },
  { name: 'Cologne', country: 'Germany', countryCode: 'DE' },
  { name: 'Stuttgart', country: 'Germany', countryCode: 'DE' },
  { name: 'Dusseldorf', country: 'Germany', countryCode: 'DE' },
  { name: 'Leipzig', country: 'Germany', countryCode: 'DE' },
  { name: 'Hanover', country: 'Germany', countryCode: 'DE' },
  { name: 'Amsterdam', country: 'Netherlands', countryCode: 'NL' },
  { name: 'Rotterdam', country: 'Netherlands', countryCode: 'NL' },
  { name: 'The Hague', country: 'Netherlands', countryCode: 'NL' },
  { name: 'Utrecht', country: 'Netherlands', countryCode: 'NL' },
  { name: 'Eindhoven', country: 'Netherlands', countryCode: 'NL' },
  { name: 'Brussels', country: 'Belgium', countryCode: 'BE' },
  { name: 'Antwerp', country: 'Belgium', countryCode: 'BE' },
  { name: 'Ghent', country: 'Belgium', countryCode: 'BE' },
  { name: 'Luxembourg City', country: 'Luxembourg', countryCode: 'LU' },
  { name: 'Zurich', country: 'Switzerland', countryCode: 'CH' },
  { name: 'Geneva', country: 'Switzerland', countryCode: 'CH' },
  { name: 'Basel', country: 'Switzerland', countryCode: 'CH' },
  { name: 'Bern', country: 'Switzerland', countryCode: 'CH' },
  { name: 'Lausanne', country: 'Switzerland', countryCode: 'CH' },
  { name: 'Vienna', country: 'Austria', countryCode: 'AT' },
  { name: 'Salzburg', country: 'Austria', countryCode: 'AT' },
  { name: 'Graz', country: 'Austria', countryCode: 'AT' },
  { name: 'Dublin', country: 'Ireland', countryCode: 'IE' },
  { name: 'Cork', country: 'Ireland', countryCode: 'IE' },
  { name: 'Galway', country: 'Ireland', countryCode: 'IE' },

  // Europe - Southern
  { name: 'Madrid', country: 'Spain', countryCode: 'ES' },
  { name: 'Barcelona', country: 'Spain', countryCode: 'ES' },
  { name: 'Valencia', country: 'Spain', countryCode: 'ES' },
  { name: 'Seville', country: 'Spain', countryCode: 'ES' },
  { name: 'Bilbao', country: 'Spain', countryCode: 'ES' },
  { name: 'Malaga', country: 'Spain', countryCode: 'ES' },
  { name: 'Lisbon', country: 'Portugal', countryCode: 'PT' },
  { name: 'Porto', country: 'Portugal', countryCode: 'PT' },
  { name: 'Rome', country: 'Italy', countryCode: 'IT' },
  { name: 'Milan', country: 'Italy', countryCode: 'IT' },
  { name: 'Turin', country: 'Italy', countryCode: 'IT' },
  { name: 'Florence', country: 'Italy', countryCode: 'IT' },
  { name: 'Naples', country: 'Italy', countryCode: 'IT' },
  { name: 'Bologna', country: 'Italy', countryCode: 'IT' },
  { name: 'Venice', country: 'Italy', countryCode: 'IT' },
  { name: 'Athens', country: 'Greece', countryCode: 'GR' },
  { name: 'Thessaloniki', country: 'Greece', countryCode: 'GR' },
  { name: 'Malta', country: 'Malta', countryCode: 'MT' },
  { name: 'Monaco', country: 'Monaco', countryCode: 'MC' },

  // Europe - Northern
  { name: 'Stockholm', country: 'Sweden', countryCode: 'SE' },
  { name: 'Gothenburg', country: 'Sweden', countryCode: 'SE' },
  { name: 'Malmo', country: 'Sweden', countryCode: 'SE' },
  { name: 'Copenhagen', country: 'Denmark', countryCode: 'DK' },
  { name: 'Aarhus', country: 'Denmark', countryCode: 'DK' },
  { name: 'Oslo', country: 'Norway', countryCode: 'NO' },
  { name: 'Bergen', country: 'Norway', countryCode: 'NO' },
  { name: 'Helsinki', country: 'Finland', countryCode: 'FI' },
  { name: 'Tampere', country: 'Finland', countryCode: 'FI' },
  { name: 'Reykjavik', country: 'Iceland', countryCode: 'IS' },

  // Europe - Eastern
  { name: 'Warsaw', country: 'Poland', countryCode: 'PL' },
  { name: 'Krakow', country: 'Poland', countryCode: 'PL' },
  { name: 'Wroclaw', country: 'Poland', countryCode: 'PL' },
  { name: 'Gdansk', country: 'Poland', countryCode: 'PL' },
  { name: 'Prague', country: 'Czech Republic', countryCode: 'CZ' },
  { name: 'Brno', country: 'Czech Republic', countryCode: 'CZ' },
  { name: 'Budapest', country: 'Hungary', countryCode: 'HU' },
  { name: 'Bucharest', country: 'Romania', countryCode: 'RO' },
  { name: 'Sofia', country: 'Bulgaria', countryCode: 'BG' },
  { name: 'Zagreb', country: 'Croatia', countryCode: 'HR' },
  { name: 'Belgrade', country: 'Serbia', countryCode: 'RS' },
  { name: 'Ljubljana', country: 'Slovenia', countryCode: 'SI' },
  { name: 'Bratislava', country: 'Slovakia', countryCode: 'SK' },
  { name: 'Tallinn', country: 'Estonia', countryCode: 'EE' },
  { name: 'Riga', country: 'Latvia', countryCode: 'LV' },
  { name: 'Vilnius', country: 'Lithuania', countryCode: 'LT' },
  { name: 'Kyiv', country: 'Ukraine', countryCode: 'UA' },
  { name: 'Lviv', country: 'Ukraine', countryCode: 'UA' },
  { name: 'Moscow', country: 'Russia', countryCode: 'RU' },
  { name: 'Saint Petersburg', country: 'Russia', countryCode: 'RU' },

  // North America
  { name: 'New York City', country: 'United States', countryCode: 'US' },
  { name: 'Los Angeles', country: 'United States', countryCode: 'US' },
  { name: 'San Francisco', country: 'United States', countryCode: 'US' },
  { name: 'Chicago', country: 'United States', countryCode: 'US' },
  { name: 'Seattle', country: 'United States', countryCode: 'US' },
  { name: 'Boston', country: 'United States', countryCode: 'US' },
  { name: 'Austin', country: 'United States', countryCode: 'US' },
  { name: 'Denver', country: 'United States', countryCode: 'US' },
  { name: 'Miami', country: 'United States', countryCode: 'US' },
  { name: 'Atlanta', country: 'United States', countryCode: 'US' },
  { name: 'Washington D.C.', country: 'United States', countryCode: 'US' },
  { name: 'Dallas', country: 'United States', countryCode: 'US' },
  { name: 'Houston', country: 'United States', countryCode: 'US' },
  { name: 'Philadelphia', country: 'United States', countryCode: 'US' },
  { name: 'Phoenix', country: 'United States', countryCode: 'US' },
  { name: 'San Diego', country: 'United States', countryCode: 'US' },
  { name: 'Minneapolis', country: 'United States', countryCode: 'US' },
  { name: 'Portland', country: 'United States', countryCode: 'US' },
  { name: 'Detroit', country: 'United States', countryCode: 'US' },
  { name: 'San Jose', country: 'United States', countryCode: 'US' },
  { name: 'Palo Alto', country: 'United States', countryCode: 'US' },
  { name: 'Toronto', country: 'Canada', countryCode: 'CA' },
  { name: 'Vancouver', country: 'Canada', countryCode: 'CA' },
  { name: 'Montreal', country: 'Canada', countryCode: 'CA' },
  { name: 'Calgary', country: 'Canada', countryCode: 'CA' },
  { name: 'Ottawa', country: 'Canada', countryCode: 'CA' },
  { name: 'Edmonton', country: 'Canada', countryCode: 'CA' },
  { name: 'Waterloo', country: 'Canada', countryCode: 'CA' },
  { name: 'Mexico City', country: 'Mexico', countryCode: 'MX' },
  { name: 'Guadalajara', country: 'Mexico', countryCode: 'MX' },
  { name: 'Monterrey', country: 'Mexico', countryCode: 'MX' },

  // South America
  { name: 'Sao Paulo', country: 'Brazil', countryCode: 'BR' },
  { name: 'Rio de Janeiro', country: 'Brazil', countryCode: 'BR' },
  { name: 'Brasilia', country: 'Brazil', countryCode: 'BR' },
  { name: 'Belo Horizonte', country: 'Brazil', countryCode: 'BR' },
  { name: 'Curitiba', country: 'Brazil', countryCode: 'BR' },
  { name: 'Buenos Aires', country: 'Argentina', countryCode: 'AR' },
  { name: 'Cordoba', country: 'Argentina', countryCode: 'AR' },
  { name: 'Santiago', country: 'Chile', countryCode: 'CL' },
  { name: 'Lima', country: 'Peru', countryCode: 'PE' },
  { name: 'Bogota', country: 'Colombia', countryCode: 'CO' },
  { name: 'Medellin', country: 'Colombia', countryCode: 'CO' },
  { name: 'Montevideo', country: 'Uruguay', countryCode: 'UY' },
  { name: 'Quito', country: 'Ecuador', countryCode: 'EC' },
  { name: 'Caracas', country: 'Venezuela', countryCode: 'VE' },

  // Asia - East
  { name: 'Tokyo', country: 'Japan', countryCode: 'JP' },
  { name: 'Osaka', country: 'Japan', countryCode: 'JP' },
  { name: 'Yokohama', country: 'Japan', countryCode: 'JP' },
  { name: 'Nagoya', country: 'Japan', countryCode: 'JP' },
  { name: 'Kyoto', country: 'Japan', countryCode: 'JP' },
  { name: 'Seoul', country: 'Korea (South)', countryCode: 'KR' },
  { name: 'Busan', country: 'Korea (South)', countryCode: 'KR' },
  { name: 'Beijing', country: 'China', countryCode: 'CN' },
  { name: 'Shanghai', country: 'China', countryCode: 'CN' },
  { name: 'Shenzhen', country: 'China', countryCode: 'CN' },
  { name: 'Guangzhou', country: 'China', countryCode: 'CN' },
  { name: 'Hangzhou', country: 'China', countryCode: 'CN' },
  { name: 'Chengdu', country: 'China', countryCode: 'CN' },
  { name: 'Nanjing', country: 'China', countryCode: 'CN' },
  { name: 'Wuhan', country: 'China', countryCode: 'CN' },
  { name: 'Hong Kong', country: 'China', countryCode: 'HK' },
  { name: 'Taipei', country: 'Taiwan', countryCode: 'TW' },

  // Asia - Southeast
  { name: 'Singapore', country: 'Singapore', countryCode: 'SG' },
  { name: 'Bangkok', country: 'Thailand', countryCode: 'TH' },
  { name: 'Kuala Lumpur', country: 'Malaysia', countryCode: 'MY' },
  { name: 'Jakarta', country: 'Indonesia', countryCode: 'ID' },
  { name: 'Bali', country: 'Indonesia', countryCode: 'ID' },
  { name: 'Ho Chi Minh City', country: 'Vietnam', countryCode: 'VN' },
  { name: 'Hanoi', country: 'Vietnam', countryCode: 'VN' },
  { name: 'Manila', country: 'Philippines', countryCode: 'PH' },

  // Asia - South
  { name: 'Bangalore', country: 'India', countryCode: 'IN' },
  { name: 'Mumbai', country: 'India', countryCode: 'IN' },
  { name: 'Delhi', country: 'India', countryCode: 'IN' },
  { name: 'Hyderabad', country: 'India', countryCode: 'IN' },
  { name: 'Chennai', country: 'India', countryCode: 'IN' },
  { name: 'Pune', country: 'India', countryCode: 'IN' },
  { name: 'Kolkata', country: 'India', countryCode: 'IN' },
  { name: 'Dhaka', country: 'Bangladesh', countryCode: 'BD' },
  { name: 'Karachi', country: 'Pakistan', countryCode: 'PK' },
  { name: 'Lahore', country: 'Pakistan', countryCode: 'PK' },
  { name: 'Colombo', country: 'Sri Lanka', countryCode: 'LK' },

  // Middle East
  { name: 'Dubai', country: 'United Arab Emirates', countryCode: 'AE' },
  { name: 'Abu Dhabi', country: 'United Arab Emirates', countryCode: 'AE' },
  { name: 'Tel Aviv', country: 'Israel', countryCode: 'IL' },
  { name: 'Jerusalem', country: 'Israel', countryCode: 'IL' },
  { name: 'Riyadh', country: 'Saudi Arabia', countryCode: 'SA' },
  { name: 'Jeddah', country: 'Saudi Arabia', countryCode: 'SA' },
  { name: 'Doha', country: 'Qatar', countryCode: 'QA' },
  { name: 'Manama', country: 'Bahrain', countryCode: 'BH' },
  { name: 'Kuwait City', country: 'Kuwait', countryCode: 'KW' },
  { name: 'Muscat', country: 'Oman', countryCode: 'OM' },
  { name: 'Amman', country: 'Jordan', countryCode: 'JO' },
  { name: 'Beirut', country: 'Lebanon', countryCode: 'LB' },
  { name: 'Istanbul', country: 'Turkey', countryCode: 'TR' },
  { name: 'Ankara', country: 'Turkey', countryCode: 'TR' },
  { name: 'Izmir', country: 'Turkey', countryCode: 'TR' },

  // Africa
  { name: 'Cairo', country: 'Egypt', countryCode: 'EG' },
  { name: 'Alexandria', country: 'Egypt', countryCode: 'EG' },
  { name: 'Casablanca', country: 'Morocco', countryCode: 'MA' },
  { name: 'Cape Town', country: 'South Africa', countryCode: 'ZA' },
  { name: 'Johannesburg', country: 'South Africa', countryCode: 'ZA' },
  { name: 'Durban', country: 'South Africa', countryCode: 'ZA' },
  { name: 'Pretoria', country: 'South Africa', countryCode: 'ZA' },
  { name: 'Lagos', country: 'Nigeria', countryCode: 'NG' },
  { name: 'Abuja', country: 'Nigeria', countryCode: 'NG' },
  { name: 'Nairobi', country: 'Kenya', countryCode: 'KE' },
  { name: 'Accra', country: 'Ghana', countryCode: 'GH' },
  { name: 'Tunis', country: 'Tunisia', countryCode: 'TN' },
  { name: 'Addis Ababa', country: 'Ethiopia', countryCode: 'ET' },
  { name: 'Algiers', country: 'Algeria', countryCode: 'DZ' },

  // Oceania
  { name: 'Sydney', country: 'Australia', countryCode: 'AU' },
  { name: 'Melbourne', country: 'Australia', countryCode: 'AU' },
  { name: 'Brisbane', country: 'Australia', countryCode: 'AU' },
  { name: 'Perth', country: 'Australia', countryCode: 'AU' },
  { name: 'Adelaide', country: 'Australia', countryCode: 'AU' },
  { name: 'Canberra', country: 'Australia', countryCode: 'AU' },
  { name: 'Auckland', country: 'New Zealand', countryCode: 'NZ' },
  { name: 'Wellington', country: 'New Zealand', countryCode: 'NZ' },
  { name: 'Christchurch', country: 'New Zealand', countryCode: 'NZ' },
];

// Helper functions for searching
export function searchCountries(query: string): Country[] {
  const normalizedQuery = query.toLowerCase().trim();
  if (!normalizedQuery) return COUNTRIES;

  return COUNTRIES.filter(country =>
    country.name.toLowerCase().includes(normalizedQuery) ||
    country.code.toLowerCase() === normalizedQuery
  );
}

export function searchCities(query: string): City[] {
  const normalizedQuery = query.toLowerCase().trim();
  if (!normalizedQuery) return CITIES;

  return CITIES.filter(city =>
    city.name.toLowerCase().includes(normalizedQuery) ||
    city.country.toLowerCase().includes(normalizedQuery)
  );
}

// Get countries list as simple string array (for backward compatibility)
export function getCountryNames(): string[] {
  return COUNTRIES.map(c => c.name);
}

// Get cities list as simple string array (for backward compatibility)
export function getCityNames(): string[] {
  return CITIES.map(c => `${c.name}, ${c.country}`);
}

// Get city display name
export function getCityDisplayName(city: City): string {
  return `${city.name}, ${city.country}`;
}
